version: '{branch}-{build}-no-release'
image: Visual Studio 2017
environment:
  nodejs_version: "8"
install:
- cmd: git submodule sync
- cmd: git submodule update --recursive --init
- ps: Install-Product node $env:nodejs_version
cache:
- 'Clients\Xamarin.Interactive.Client\ClientApp\node_modules'
- 'Clients\Xamarin.Interactive.Client.Web\node_modules'
- '%USERPROFILE%\.nuget\packages'
build_script:
- cmd: msbuild build.proj /p:Configuration=Release /t:UpdateBuildInfo,Restore,Build,Package
test_script:
- cmd: msbuild build.proj /t:Test
artifacts:
- path: _artifacts\*.msi
  name: Installer