version: '{branch}-{build}-no-release'
image: Visual Studio 2017
install:
- cmd: >-
    git submodule sync

    git submodule update --recursive --init
cache:
- node_modules
- '%USERPROFILE%\.nuget\packages'
build_script:
- cmd: msbuild build.proj /p:Configuration=Release /t:UpdateBuildInfo,Restore,Build,Package
test_script:
- cmd: msbuild build.proj /t:Test
artifacts:
- path: _artifacts\*.msi
  name: Installer