sudo: false
language: csharp
mono: none
dotnet: 2.1.301

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -O -L https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe

cache:
  yarn: true

script:
- dotnet build build.proj
- dotnet msbuild build.proj /t:Test
- dotnet msbuild build.proj /t:Package